### ISSUE TITLE
Manage session from TextChatFragment

### ISSUE THREAD

**Issue by marinaserranomontes** [opentok/accelerator-textchat-android#27]
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/opentok/accelerator-core-ios/blob/master/README.md) 
- [ ] I have searched [existing issues](https://github.com/opentok/accelerator-core-ios/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s): 1.0.2
- iOS/Android/Browser version(s): Android
- Devices/Simulators/Machine affected:
- Reproducible in the demo project? (Yes/No): Yes
- Related issues:

## Bug report
The session in the constructor is not connected. Manage a disconnected session from the accelerator textchat
#### Expected behavior
The accelerator textchat should detect if the session is connected or not, and it should manage it. 

#### Actual behavior
Right now, we are supposing the session is connected from the app before to start sending/receiving messages.

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by igorwojda** [comment]
As part of the cleanup, we will leave it W for now (we would need to redesign the OTAccelerator session to dispatch connection statuses)
