### ISSUE TITLE
Wrong parameters sequence in ReadMe document vs actual Constructor

### ISSUE THREAD

**Issue by wazzah-iftikhar** [opentok/accelerator-textchat-android#44]
#### Expected behavior

> The ReadMe document says while initializing OTAcceleratorSession object pass parameters in this  sequence

OTAcceleratorSession mSession = new OTAcceleratorSession (context, sessionId, apikey);

#### Actual behavior

> While the actual defination requires the parameters to be passed in this is sequence

OTAcceleratorSession mSession = new  OTAcceleratorSession(context, apiKey, sessionId) ;

**The position of apiKey and sessionId parameters is swapped. It wasted my entire day.**

> ...

**Comment by marinaserranomontes** [comment]
Hi @wazzah-iftikhar ,

Sorry for the delayed response.

Thanks for the feedback. We have updated the README.

Regards,
Marina
