### ISSUE TITLE
TextChat Adapter should use DiffUtils to render view

### ISSUE THREAD

**Issue by Raulkg** [opentok/accelerator-textchat-android#56]
## New issue checklist

- [ ] I have read all of the [`README`](../README.md) 
- [ ] I have searched [existing issues](https://github.com/opentok/accelerator-textchat-android/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS/Android/Browser version(s):
- Devices/Simulators/Machine affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

## Bug report

Currently, we are using notifyadatper() method to update recyclerview which is prone to destroy existing rendered views and recreate all the views.

#### Expected behavior

The accelerator textchat should render only needed views

#### Actual behavior

Right now, we are using notify adapter to update and render recycler view

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

This is Enhancement

**Comment by igorwojda** [comment]
Adressed by this PR https://github.com/opentok/accelerator-textchat-android/pull/55
